import { mkdir, readdir, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ASSETS = fileURLToPath(new URL('../assets/', import.meta.url));

const pngOpts = { compressionLevel: 9, palette: true, quality: 100 };

const sets = {
  exercises: {
    src: 'wooden_dummy/Training',
    dst: 'exercises',
    fit: (pipeline) =>
      pipeline
        .resize({ width: 1536, height: 1536, fit: 'inside', withoutEnlargement: true })
        .png(pngOpts),
  },
  icons: {
    src: 'icons',
    dst: 'icons',
    fit: (pipeline) =>
      pipeline
        .resize(512, 512, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .png(pngOpts),
  },
  badges: {
    src: 'badges',
    dst: 'badges',
    fit: (pipeline) =>
      pipeline
        .resize(512, 512, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .png(pngOpts),
  },
  journey: {
    src: 'journey',
    dst: 'journey',
    fit: (pipeline) =>
      pipeline
        .resize(512, 512, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .png(pngOpts),
  },
  frames: {
    src: 'frames',
    dst: 'frames',
    fit: (pipeline) =>
      pipeline
        .resize(512, 512, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .png(pngOpts),
  },
  portraits: {
    src: 'portraits',
    dst: 'portraits',
    fit: (pipeline) =>
      pipeline
        .resize(512, 512, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .png(pngOpts),
  },
  titles: {
    src: 'titles',
    dst: 'titles',
    fit: (pipeline) =>
      pipeline
        .resize(1024, 1024, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .png(pngOpts),
  },
  onboarding: {
    src: 'onboarding',
    dst: 'onboarding',
    fit: (pipeline) =>
      pipeline
        .resize(1536, 1536, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .png(pngOpts),
  },
  backgrounds: {
    src: 'backgrounds',
    dst: 'backgrounds',
    fit: async (pipeline, src) => {
      const { width, height } = await sharp(src).metadata();
      return pipeline
        .resize(width, height, { fit: 'inside', withoutEnlargement: true })
        .flatten({ background: '#ffffff' })
        .jpeg({ quality: 85, chromaSubsampling: '4:2:0' });
    },
  },
};

const rows = [];
const track = (dst, name, from, outBytes, inBytes, dims) =>
  rows.push(
    `| ${dst}/${name} | ${dims} | ${Math.round(inBytes / 1024)} KB → ${Math.round(outBytes / 1024)} KB | ${from} |`,
  );

for (const [setName, cfg] of Object.entries(sets)) {
  const srcDir = join(ASSETS, cfg.src);
  const dstDir = join(ASSETS, cfg.dst);
  await mkdir(dstDir, { recursive: true });
  let files;
  try {
    files = (await readdir(srcDir)).filter((f) => /\.png$/i.test(f));
  } catch {
    console.log(`skip ${cfg.src}/ (no source)`);
    continue;
  }
  for (const file of files) {
    const src = join(srcDir, file);
    const ext = setName === 'backgrounds' ? 'jpg' : 'png';
    const dst = join(dstDir, file.replace(/\.png$/i, `.${ext}`));
    const pipeline = sharp(src);
    const fit = await cfg.fit(pipeline, src);
    const tmp = `${dst}.tmp`;
    await fit.toFile(tmp);
    await rm(dst, { force: true });
    await import('node:fs/promises').then(({ rename }) => rename(tmp, dst));
    const [inBytes, outBytes, meta] = await Promise.all([
      (await sharp(src).toBuffer()).length,
      (await sharp(dst).toBuffer()).length,
      sharp(dst).metadata(),
    ]);
    track(
      setName,
      file.replace(/\.png$/i, `.${ext}`),
      `wooden_dummy/Training` === cfg.src ? 'delivery (normalized)' : `delivery (${cfg.src}/)`,
      outBytes,
      inBytes,
      `${meta.width}×${meta.height}`,
    );
    console.log(`${setName}/${file} -> ${dst.replace(ASSETS, 'assets/')}`);
  }
  if (setName === 'exercises') {
    await rm(join(ASSETS, 'wooden_dummy', 'Training'), { recursive: true, force: true });
  } else if (setName === 'backgrounds') {
    for (const file of files) {
      await rm(join(srcDir, file), { force: true });
    }
  }
}

const credits = `# Next Move — Asset Credits & Ledger

Generated by \`scripts/normalize-assets.mjs\` (normalization + compression) from the approved AT-01..05 delivery (2026-08-10).

## Ledger

| File | Final size | Original → final | Source |
|---|---|---|---|
${rows.join('\n')}

## Image sources

All images are **AI-generated originals** produced for Next Move by the Asset Designer (in-house tooling). No stock photography, no third-party image assets. License: internal (Next Move). Any AI-artifact resembling a recognizable person is coincidental.

## Sound sources

| File | Source | License |
|---|---|---|
| click.wav | TBD — owner to supply | TBD |
| countdown.wav | TBD — owner to supply | TBD |
| exercise_end.wav | TBD — owner to supply | TBD |
| levelup.wav | Kenney CC0 (confirmation chime) — per ED-24 | CC0 1.0 |
| quest_complete.wav | TBD — owner to supply | TBD |
| rest_end.wav | TBD — owner to supply | TBD |
| rest_start.wav | TBD — owner to supply | TBD |
| victory_fanfare.wav | TBD — owner to supply | TBD |

See \`THIRD_PARTY_NOTICES.md\` for bundled third-party notices.
`;
await writeFile(join(ASSETS, 'CREDITS.md'), credits, 'utf8');
console.log('\nWrote assets/CREDITS.md');
